apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-pod
  template:
    metadata:
      labels:
        app: myapp-pod
    spec:
      containers:
      - image: taltaf913/titanic-fastapi:latest
        name: mycontainer
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc-v3
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: myapp-pod
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-svc-v3
            port:
              number: 8001
