name: CI/CD Pipeline for AKS

on:
  workflow_run:
    workflows: ["Push a Docker Image"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4

    - name: Get AKS Credentials
      run: |
       az aks get-credentials --resource-group adf --name whiztest12 --overwrite-existing
       kubectl get nodes


      # Deploy to EKS using kubectl
    - name: Deploy to EKS
      run: |
        kubectl apply -f deploy_auto_scale.yaml
        kubectl get svc
    - name: Get Service URL
      run: |
        
        kubectl get svc my-svc-v3 -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
       
  

