name: PullDockerImage
on:
  workflow_run:
    workflows: ["Push a Docker Image"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/titanic-fastapi:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f titanic-fastapi-container || true
      - name: Run Docker Container
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker run -it -d -p 8001:8001 --name=titaniceapi $DOCKER_USER/titanic-fastapi:latest
