name: PullDockerImage
on:
  workflow_run:
    workflows: ["Push a Docker Image"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Login to Docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Pull Image from Docker hub
        run: sudo docker pull $DOCKER_USER/titanic-fastapi:latest

      - name: run docker image
        run: sudo docker run -it -d -p 8001:8001 --name=titaniceapi $DOCKER_USER/titanic-fastapi:latest
