name: CI/CD Pipeline for EKS

on:
  workflow_run:
    workflows: ["Push a Docker Image"] # This refers to the name of the first workflow
    types:
      - completed

jobs:
  deploy-to-eks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Configure AWS credentials using GitHub Secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Specify your region

    # Install kubectl
    - name: Install kubectl
      run: |
        curl -LO "https://amazon-eks.s3-us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    # Install eksctl
    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin   

    - name: Create EKS cluster
      run: |
        eksctl create cluster \
          --name=r4cluster \
          --region=us-east-1 \
          --version=1.32 \
          --node-type=t2.medium \
          --nodes=2 \
          --managed \
          --asg-access

    # Update kubeconfig for your EKS cluster
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name r4cluster --region us-east-1
        eksctl get cluster
        kubectl get nodes
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm repo add eks https://aws.github.io/eks-charts
        helm repo update
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
        eksctl utils associate-iam-oidc-provider --region us-east-1 --cluster r4cluster --approve
        curl -Lo iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json
        aws iam create-policy --policy-name ALBIngressControllerIAMPolicy --policy-document file://iam-policy.json
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV
        eksctl create iamserviceaccount \
           --cluster r4cluster \
           --namespace kube-system \
           --name aws-load-balancer-controller \
           --attach-policy-arn arn:aws:iam::${ACCOUNT_ID}:policy/ALBIngressControllerIAMPolicy \
           --override-existing-serviceaccounts \
           --approve

    - name: Add EKS Helm Repo
      run: |
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml
        helm repo add eks https://aws.github.io/eks-charts
        helm repo update

    - name: Install AWS Load Balancer Controller
      run: |
        helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
           --set clusterName=r4cluster \
           --set serviceAccount.create=false \
           --set serviceAccount.name=aws-load-balancer-controller \
           --namespace kube-system
        kubectl get pods -n kube-system | grep aws-load-balancer

    # Deploy to EKS using kubectl
    - name: Deploy to EKS
      run: |
        kubectl apply -f deploy_auto_scale.yaml
        kubectl get pods
        kubectl get deployments
        kubectl expose pod myapp-pod --type=LoadBalancer --name=my-svc-v3
        echo kubectl get svc

    # Get the LoadBalancer service URL (instead of echoing the command)
    - name: Get Service URL
      run: |
        kubectl get svc my-svc-v3 -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
        echo "Service is available at: $(kubectl get svc my-svc-v3 -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')"

    # Optionally check status of the deployment
    - name: Check Deployment Status
      run: kubectl rollout status deployment/myapp-deployment
